refactor: now there are two build scripts: one for ESP-32 (brt-esp) and one for desktop (brt). On desktop, we now pass QASE_SCHEMA_VALIDATION_ENABLED to the code and also build in pboettch/json-schema-validator so that we can now do schema validation. the process will be like so: yq converts Qase yaml schemas to json, json-schema-validator then checks if the payload json matches the schema

diff --git a/brt b/brt
--- a/brt
+++ b/brt
@@ -1,2 +1,12 @@
 #!/usr/bin/env bash
-cmake -S . -B build && cmake --build build&& ./build/qase_reporter_tests
+
+# for desktop, json schema is parsed
+# and yq is required to convert from yaml to json
+if ! command -v yq &> /dev/null; then
+  echo "yq is required to convert schema.yaml to schema.json"
+  exit 1
+fi
+rm -rf build/
+cmake -S . -B build -DQASE_SCHEMA_VALIDATION=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5
+cmake --build build
+./build/qase_reporter_tests
